### PR TITLE
Include errors in the info field of the json output

### LINKED ISSUE #185: Improve error handling for the user
Currently, we include `ERROR` entries into the metrics list if an error occurs. We should make errors more obvious by including an entry in the new `info` list of the JSON-output.

Open decisions:

- [ ] Include metrics that were calculated successfully for a file or not if one of the metrics failed to be calculated. The other metrics might still provide helpful information for the user, on the other hand, that would mean that we have one entry in the `info` list and one in the regular list for such a file.

### PR DESCRIPTION
**Pull request by ResistantBear**
# Include errors in the info field of the json output

Closes #185

## Description

No longer includes "ERROR" metrics into the list of metrics in the output .json-file, but include errors in the "info" field of the .json-file. Refactors error handling accordingly.

The user is now informed about if parsing a syntax tree failed or if calculating some metrics failed for a particular file.

## Definition of Done

A PR is only ready for merge once all the following acceptance criteria are fulfilled:
* [x]  All TODOs related to this PR have been closed
* [x]  There are automated tests for newly written code and bug fixes
* [x]  All bugs discovered while working on this PR have been submitted as issues (if not already an open issue)
* [x]  Documentation ([README.md](https://github.com/MaibornWolff/metric-gardener/blob/main/README.md), [UPDATE_GRAMMARS.md](https://github.com/MaibornWolff/metric-gardener/blob/main/UPDATE_GRAMMARS.md)) has been updated

### CODE REVIEW

File: src/parser/GenericParser.ts [hunk 1]
```diff
@@ -108,17 +110,19 @@ export class GenericParser {
...
-
-            for (let i = 0; i < unsupportedFiles.length; i++) {
-                unsupportedFiles[i] = formatPrintPath(unsupportedFiles[i], this.config);
+            for (const [sourceFile, metricsMap] of promisesResults) {
+                const printPath = formatPrintPath(sourceFile.filePath, this.config);
+                if (isErrorFile(sourceFile)) {
+                    errorFiles.set(printPath, sourceFile.error);
+                } else {
+                    fileMetrics.set(printPath, metricsMap);
+                }
```
Comment (clemens-mw) [inline src/parser/GenericParser.ts:119]:
```suggestion
                if (isErrorFile(sourceFile)) {
                    errorFiles.set(printPath, sourceFile.error);
                } else {
                    fileMetrics.set(printPath, metricsMap);
                }
                if (sourceFile instanceof UnsupportedFile) {
                    unsupportedFiles.push(printPath);
                }
```

File: src/parser/metrics/Metric.ts [hunk 2]
```diff
@@ -117,3 +117,19 @@ export class ParsedFile extends SourceFile {
...
+
+    constructor(filePath: string, error: Error) {
+        super(filePath);
+        this.error = error;
+    }
+}
+
+export function isErrorFile(file: SourceFile): file is ErrorFile {
+    return (file as ErrorFile).error !== undefined;
+}
```
Comment (clemens-mw) [inline src/parser/metrics/Metric.ts:135]: use instanceof instead?
also for isParsedFile?
=> new issue?

File: src/parser/MetricCalculator.ts [hunk 3]
```diff
@@ -92,6 +89,6 @@ export class MetricCalculator {
             metricResults.set(result.metricName, result);
         }
 
-        return [formatPrintPath(sourceFile.filePath, this.#config), metricResults];
```
Comment (clemens-mw) [inline src/parser/MetricCalculator.ts:95]: `this.#config` is unused now
=> delete completely?

File: src/parser/MetricCalculator.ts
Comment (clemens-mw) [inline src/parser/MetricCalculator.ts:1]: how to handle errors in line 75?

File: src/commands/outputMetrics.ts [hunk 4]
```diff
@@ -13,7 +13,7 @@ interface OutputNode {
 
 interface OutputInfoNode {
     name: string;
-    type: "File";
+    type: string;
```
[the remark this answers is not in the document]
Comment (ResistantBear) [reply src/commands/outputMetrics.ts]: That was changed to `string` in PR #143, I did not want to provoke a merge conflict here. 
We may change that to `FileType` now, however.

File: src/parser/metrics/Metric.ts [hunk 5]
```diff
@@ -117,3 +117,19 @@ export class ParsedFile extends SourceFile {
 export function isParsedFile(file: SourceFile): file is ParsedFile {
     return (file as ParsedFile).language !== undefined && (file as ParsedFile).tree !== undefined;
 }
+
+export class ErrorFile extends SourceFile {
+    /**
+     * Error that occured while processing the file.
```
[the remark this answers is not in the document]
Comment (ResistantBear) [reply src/parser/metrics/Metric.ts:137]: Jup

File: src/parser/GenericParser.test.ts [hunk 6]
```diff
@@ -304,7 +304,7 @@ describe("GenericParser.calculateMetrics()", () => {
             if (file === null || getFileExtension(file.filePath) !== "cpp") {
```
[the remark this answers is not in the document]
Comment (ResistantBear) [reply src/parser/GenericParser.test.ts:309]: Jep

File: src/parser/GenericParser.ts [hunk 7]
```diff
@@ -85,13 +85,15 @@ export class GenericParser {
             for (const file of treeParseResults) {
```
[the remark this answers is not in the document]
Comment (ResistantBear) [reply src/parser/GenericParser.ts:86]: Should work. On the other hand, having two `filter` calls on `treeParseResults` should be less efficient than traversing it just once.

But checking for `isErrorFile` should be indeed redundant when already checking for `isParseFile`.

File: src/parser/metrics/Metric.ts (hunk 2 above)
Comment (ResistantBear) [reply src/parser/metrics/Metric.ts:149]: Well, as SourceFile is a class now, that should work. However, I still hesitate to use instanceof because Ruben mentioned an issue with the jest test framework that can break the `instanceof` operator. See also #20.

File: src/parser/MetricCalculator.ts (hunk 3 above)
Comment (ResistantBear) [reply src/parser/MetricCalculator.ts]: Right

File: src/parser/MetricCalculator.ts
Comment (ResistantBear) [reply src/parser/MetricCalculator.ts:1]: Should be fixed in the meantime.
There is still an open question mentioned in #185 however on how to deal with the other metrics for a file for which only some metric calculations failed. For now, I decided to include them in the .json file.

File: src/parser/GenericParser.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (clemens-mw) [reply src/parser/GenericParser.ts:86]: what do you mean with two filter calls?

[the remark this answers is not in the document]
Comment (ResistantBear) [reply src/parser/GenericParser.ts:92]: The thing were we "add unsupported files later"

[the remark this answers is not in the document]
Comment (clemens-mw) [reply src/parser/GenericParser.ts:92]: we need to loop through the results again in line 116 anyways
just add them there?

[the remark this answers is not in the document]
Comment (ResistantBear) [reply src/parser/GenericParser.ts:92]: Thats another list (promisesResults vs. treeParseResults). 
But since we introduced `LinesOfCodeRawText`, the unsupported files should also be included in that list. Before that, we filtered them out of that before calling `MetricCalculator`. So yes, we could probably also add them there.

[the remark this answers is not in the document]
Comment (ResistantBear) [reply src/parser/GenericParser.ts]: Changed that accordingly

[the remark this answers is not in the document]
Comment (clemens-mw) [reply src/parser/GenericParser.ts]: perfect

File: src/parser/GenericParser.ts [hunk 8]
```diff
@@ -42,69 +42,49 @@ export class GenericParser {
...
+                    const printPath = formatPrintPath(sourceFile.filePath, this.config);
+                    errorFiles.push(printPath);
+
+                    console.error("Error while parsing the syntax tree for the file " + printPath);
+                    console.error(sourceFile.error);
+                } else if (isParsedFile(sourceFile)) {
+                    // Do only include files for calculating the coupling metrics
+                    // that are supported and have been parsed successfully:
+                    filesForCouplingMetrics.push(sourceFile);
                 }
```
Comment (ResistantBear) [inline src/parser/GenericParser.ts:85]: I had to change this again because the ErrorFile would not be handled when `this.config.parseMetrics` would evaluate to `false`, as then, there would be no further promise chain.

File: src/parser/GenericParser.test.ts [hunk 9]
```diff
@@ -306,12 +327,97 @@ describe("GenericParser.calculateMetrics()", () => {
...
+                FileMetric.classes,
+                {
+                    metricName: FileMetric.classes,
+                    error: new Error("Classes metric is to difficult for this program!"),
+                },
+            ],
+            [
+                FileMetric.functions,
+                {
+                    metricName: FileMetric.classes,
```
Comment (clemens-mw) [inline src/parser/GenericParser.test.ts:401]:
```suggestion
                    metricName: FileMetric.functions,
```

**Review by clemens-mw — CHANGES_REQUESTED** [review]
minor issue, otherwise perfect :)

File: src/parser/GenericParser.ts [hunk 10]
```diff
@@ -42,69 +42,49 @@ export class GenericParser {
...
             }
 
-            const fileMetricPromises: Promise<[string, FileMetricResults]>[] = [];
+            const fileMetricPromises: Promise<[SourceFile, FileMetricResults]>[] = [];
 
             if (this.config.parseMetrics) {
-                const metricsParser = new MetricCalculator(this.config);
+                const metricsParser = new MetricCalculator();
 
                 for (const [filePath, parsePromise] of parsePromises) {
```
Comment (clemens-mw) [inline src/parser/GenericParser.ts:61]: filePath is not needed anymore
```suggestion
                for (const parsePromise of parsePromises) {
```

File: src/parser/GenericParser.ts [hunk 11]
```diff
@@ -42,69 +42,49 @@ export class GenericParser {
     async calculateMetrics() {
         const fileMetrics = new Map<string, FileMetricResults>();
         const unsupportedFiles: string[] = [];
+        const errorFiles: string[] = [];
         let couplingMetrics = {} as CouplingResult;
 
         try {
             const filePathGenerator = findFilesAsync(this.config);
-            const parsePromises = new Map<string, Promise<SourceFile | null>>();
+            const parsePromises = new Map<string, Promise<SourceFile>>();
```
Comment (clemens-mw) [inline src/parser/GenericParser.ts:50]: map is not needed anymore (see below)
```suggestion
            const parsePromises: Promise<SourceFile>[] = [];
```

File: src/parser/GenericParser.ts [hunk 12]
```diff
@@ -114,17 +94,32 @@ export class GenericParser {
...
+                        console.error(
+                            "Error while calculating the metric " +
+                                metricError.metricName +
+                                " on the file " +
+                                sourceFile.filePath,
+                        );
+                        console.error(metricError.error);
+                    }
+                    if (!isParsedFile(sourceFile)) {
+                        unsupportedFiles.push(formatPrintPath(sourceFile.filePath, this.config));
```
Comment (clemens-mw) [inline src/parser/GenericParser.ts:114]: don't calculate print path again
```suggestion
                        unsupportedFiles.push(printPath);
```

**Review by clemens-mw — CHANGES_REQUESTED** [review]

**Review by clemens-mw — APPROVED** [review]
